name: flutter_preintern_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.7.2
  jiffy: ^6.4.4
  flutter_bloc: ^9.1.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/img/
    - asset/img/icon/
    - asset/img/icon/lang/
    - asset/img/logo/
    - asset/img/deco/
    - asset/img/logo/external/
  fonts:
    - family: VarelaRound
      fonts:
        - asset: asset/font/Varela_Round/VarelaRound-Regular.ttf
    - family: Mitr
      fonts:
        - asset: asset/font/Mitr/Mitr-Regular.ttf
        - asset: asset/font/Mitr/Mitr-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Mitr/Mitr-Light.ttf
          weight: 300
        - asset: asset/font/Mitr/Mitr-Medium.ttf
          weight: 500
        - asset: asset/font/Mitr/Mitr-SemiBold.ttf
          weight: 600
        - asset: asset/font/Mitr/Mitr-Bold.ttf
          weight: 700